name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Compute Bundle Version
        id: compute-version
        run: |
          VERSION=$(date +"%d-%b-%Y")-$(git rev-parse --short=6 HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Front-end bundle version: $VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Inject version meta tag into index.template.html
        run: |
          VERSION=${{ steps.compute-version.outputs.VERSION }}
          sed -i 's|</head>|<meta name="bundle-version" content="'$VERSION'"></head>|' templates/index.template.html
        working-directory: ./AWE

      - name: Install dependencies
        run: npm ci
        working-directory: ./AWE

      - name: Build
        run: npm run build
        working-directory: ./AWE

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "acc-web-vis-56233468509d"
          heroku_email: "bogdanviziru18@gmail.com"
          appdir: "AWE"
